version: "3.78

services: 

    flask:
        build: ./flask
        container_name: flask
        restart: always
        environment: 
            - APP_NAME=MyFlaskApp
        expose: 
            - 8080

    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "80:80"
    
    postgres:
        build: ./postgres
        container_name: postgres
        restart: always
        ports:
            -""